USE [master]
GO
/****** Object:  Database [PersonalBlog1]    Script Date: 7/20/2021 8:07:37 PM ******/
CREATE DATABASE [PersonalBlog1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PersonalBlog1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PersonalBlog1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PersonalBlog1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PersonalBlog1.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PersonalBlog1] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PersonalBlog1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PersonalBlog1] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [PersonalBlog1] SET ANSI_NULLS ON 
GO
ALTER DATABASE [PersonalBlog1] SET ANSI_PADDING ON 
GO
ALTER DATABASE [PersonalBlog1] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [PersonalBlog1] SET ARITHABORT ON 
GO
ALTER DATABASE [PersonalBlog1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PersonalBlog1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PersonalBlog1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PersonalBlog1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PersonalBlog1] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [PersonalBlog1] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [PersonalBlog1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PersonalBlog1] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [PersonalBlog1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PersonalBlog1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PersonalBlog1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PersonalBlog1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PersonalBlog1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PersonalBlog1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PersonalBlog1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PersonalBlog1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PersonalBlog1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PersonalBlog1] SET RECOVERY FULL 
GO
ALTER DATABASE [PersonalBlog1] SET  MULTI_USER 
GO
ALTER DATABASE [PersonalBlog1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PersonalBlog1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PersonalBlog1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PersonalBlog1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PersonalBlog1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PersonalBlog1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PersonalBlog1] SET QUERY_STORE = OFF
GO
USE [PersonalBlog1]
GO
/****** Object:  Table [dbo].[Articles]    Script Date: 7/20/2021 8:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Articles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[Text] [nvarchar](max) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[BlogId] [int] NULL,
 CONSTRAINT [PK_Articles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ArticleTagMap]    Script Date: 7/20/2021 8:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ArticleTagMap](
	[ArticleId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_ArticleTagMap] PRIMARY KEY CLUSTERED 
(
	[ArticleId] ASC,
	[TagId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Blogs]    Script Date: 7/20/2021 8:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Blogs](
	[BlogId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Blogs] PRIMARY KEY CLUSTERED 
(
	[BlogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 7/20/2021 8:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tags]    Script Date: 7/20/2021 8:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tags](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Tag] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 7/20/2021 8:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Login] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](max) NOT NULL,
	[NormalizedLogin] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserToRoles]    Script Date: 7/20/2021 8:07:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserToRoles](
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_UserToRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Articles]  WITH CHECK ADD  CONSTRAINT [FK__Articles__BlogId__59063A47] FOREIGN KEY([BlogId])
REFERENCES [dbo].[Blogs] ([BlogId])
GO
ALTER TABLE [dbo].[Articles] CHECK CONSTRAINT [FK__Articles__BlogId__59063A47]
GO
ALTER TABLE [dbo].[ArticleTagMap]  WITH CHECK ADD FOREIGN KEY([ArticleId])
REFERENCES [dbo].[Articles] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ArticleTagMap]  WITH CHECK ADD  CONSTRAINT [FK__ArticleTa__TagId__6C190EBB] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tags] ([Id])
GO
ALTER TABLE [dbo].[ArticleTagMap] CHECK CONSTRAINT [FK__ArticleTa__TagId__6C190EBB]
GO
ALTER TABLE [dbo].[ArticleTagMap]  WITH CHECK ADD FOREIGN KEY([TagId])
REFERENCES [dbo].[Tags] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserToRoles]  WITH CHECK ADD  CONSTRAINT [FK__UserToRol__UserI__02FC7413] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserToRoles] CHECK CONSTRAINT [FK__UserToRol__UserI__02FC7413]
GO
USE [master]
GO
ALTER DATABASE [PersonalBlog1] SET  READ_WRITE 
GO
